# This file configures golangci-lint.
# Reference: https://golangci-lint.run/usage/configuration/

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - whitespace
