name: Authorize Commit Signing
description: >
  Verify signature of a signed commit using Beyond Identity.

inputs:
  api_token:
    description: >
      API token for the Beyond Identity key management API. Should be stored as
      a secret in your repository, and referenced as, e.g.

          api_token: {{ secrets.BYNDID_KEY_MGMT_API_TOKEN }}
    required: true
  ref:
    description: >
      The commit reference to check. Defaults to HEAD, which will be the ref
      checked out by `actions/checkout`.
    required: false
    default: "HEAD"
  allowlist_config_file_path:
    description: >
      The file path where the allowlist config file is stored from the allowlist 
      repo root. See README on how to configure allowlist.
    required: false


runs:
  using: docker
  image: docker://docker.io/byndid/auth-commit-sig:0.7.0-rc8
  env:
    API_TOKEN: ${{ inputs.api_token }}
    ALLOWLIST_CONFIG_FILE_PATH: ${{ inputs.allowlist_config_file_path }}
  args:
    - "-ref=${{ inputs.ref }}"

branding:
  icon: user-check
  color: blue
