ARG VERSION
FROM auth-commit-sig-builder:${VERSION} as builder

FROM docker.io/library/debian:12-slim@sha256:e899040a73d36e2b36fa33216943539d9957cba8172b858097c2cabcdb20a3e2

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates
RUN update-ca-certificates

COPY --from=builder /out/action /bin/action

ENTRYPOINT ["/bin/action"]
